In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [85]:
# num_samples = int(input("Digite o número de amostras: "))
# mean_arrival_time = float(input("Digite o tempo médio de chegada das amostras: "))
# mean_departure_time = float(input("Digite o tempo médio de saída das amostras: "))

num_samples = 40
mean_arrival_time = 1
mean_departure_time = 2

In [86]:
print("\nTempo de chegada | Tipo de evento | Número de amostras\n")

n = 0
simul_time = 0
data = []
for i in range(num_samples):
    arrival_time = np.random.exponential(scale=mean_arrival_time)
    departure_time = np.random.exponential(scale=mean_departure_time)

    if n == 0:
        simul_time += arrival_time
        print(f"{simul_time:8.4f} \t\t{'Chegada':14} {n:2} => {n+1:2}")
        data.append([f"{simul_time:8.4f}", f"{'Chegada'}", f"{n}", f"{n+1}"])
        n += 1
    else:
        if arrival_time < departure_time:
            simul_time += arrival_time
            print(f"{simul_time:8.4f} \t\t{'Chegada':14} {n:2} => {n+1:2}")
            data.append([f"{simul_time:8.4f}", f"{'Chegada'}", f"{n}", f"{n+1}"])
            n += 1
        else:
            simul_time += departure_time
            print(f"{simul_time:8.4f} \t\t{'Saída':14} {n:2} => {n-1:2}")
            data.append([f"{simul_time:8.4f}", f"{'Saída'}", f"{n}", f"{n+1}"])
            n -= 1

print(f"\nNúmero de amostras na fila ao final da simulação: {n}")
print(f"Tempo total da simulação: {simul_time:.4f}")
print(
    f"Tempo médio de espera na fila: {(simul_time/num_samples - mean_arrival_time):.4f}")

Tempo de chegada | Tipo de evento | Número de amostras

  0.1369 		Chegada         0 =>  1
  2.1300 		Chegada         1 =>  2
  2.7518 		Chegada         2 =>  3
  3.1123 		Chegada         3 =>  4
  3.1222 		Saída           4 =>  3
  3.1790 		Chegada         3 =>  4
  4.0460 		Chegada         4 =>  5
  4.7411 		Saída           5 =>  4
  5.6439 		Saída           4 =>  3
  5.6863 		Chegada         3 =>  4
  5.9843 		Saída           4 =>  3
  6.3372 		Saída           3 =>  2
  6.3849 		Chegada         2 =>  3
  7.7047 		Chegada         3 =>  4
  8.0854 		Chegada         4 =>  5
  8.1168 		Chegada         5 =>  6
  8.1349 		Chegada         6 =>  7
  8.2166 		Chegada         7 =>  8
  8.9211 		Saída           8 =>  7
  9.2993 		Chegada         7 =>  8
  9.4969 		Chegada         8 =>  9
 10.4087 		Chegada         9 => 10
 12.4729 		Saída          10 =>  9
 12.8808 		Chegada         9 => 10
 15.1530 		Chegada        10 => 11
 15.4145 		Saída          11 => 10
 15.7732 		Saída          10 =>  9
 16.1061 		Chegada         9 => 10
 16.1604 		Saída          10 =>  9
 18.7857 		Saída           9 =>  8
 18.9372 		Saída           8 =>  7
 19.4508 		Saída           7 =>  6
 19.9122 		Chegada         6 =>  7
 21.0623 		Chegada         7 =>  8
 22.1411 		Chegada         8 =>  9
 22.5993 		Chegada         9 => 10
 23.0910 		Chegada        10 => 11
 23.4231 		Saída          11 => 10
 25.4906 		Saída          10 =>  9
 25.6195 		Saída           9 =>  8

Número de amostras na fila ao final da simulação: 8
Tempo total da simulação: 25.6195
Tempo médio de espera na fila: -0.3595

In [82]:
df = pd.DataFrame(data, columns=['Tempo de Chegada', 'Tipo de Evento', 'Antes', 'Depois'])
df

   Tempo de Chegada Tipo de Evento Antes Depois
0            0.3673        Chegada     0      1
1            0.6136          Saída     1      2
2            2.8564        Chegada     0      1
3            2.9947        Chegada     1      2
4            4.0001          Saída     2      3
5            5.2476        Chegada     1      2
6            6.2795        Chegada     2      3
7            8.8091          Saída     3      4
8           10.1969        Chegada     2      3
9           11.8056          Saída     3      4
10          12.2585        Chegada     2      3
11          13.3572          Saída     3      4
12          14.3431        Chegada     2      3
13          15.4524        Chegada     3      4
14          17.5394        Chegada     4      5
15          23.0807        Chegada     5      6
16          24.1339          Saída     6      7
17          25.2309          Saída     5      6
18          26.0383        Chegada     4      5
19          26.2439          Saída     5      6
20          27.1421          Saída     4      5
21          27.9265        Chegada     3      4
22          31.0090        Chegada     4      5
23          32.2727          Saída     5      6
24          32.6584        Chegada     4      5
25          34.3209        Chegada     5      6
26          36.1433        Chegada     6      7
27          39.4403        Chegada     7      8
28          39.5225        Chegada     8      9
29          39.9993        Chegada     9     10
30          40.1631        Chegada    10     11
31          40.2043          Saída    11     12
32          40.2488          Saída    10     11
33          40.6175        Chegada     9     10
34          41.0838        Chegada    10     11
35          41.1000          Saída    11     12
36          41.2031          Saída    10     11
37          42.2302          Saída     9     10
38          42.3129        Chegada     8      9
39          43.7575        Chegada     9     10